# Using and image with node 20.10.0 lite
FROM node:20.10.0-alpine

# Install pnpm
RUN npm install -g pnpm

# Create working directory
WORKDIR /app

# Copy prisma files
COPY prisma ./prisma

# Copy all rest of the files
COPY . .

# Install dependencies
RUN npm install

# Start the api in dev mode
CMD npm run build-container
